### ISSUE TITLE
Regarding 'Full Screen' option in style guide

### ISSUE THREAD

**Issue by paulgoodfield** [towardstudio/websitedocumentation#9]
Wondering if the text for this should say 'Toggle Sidebar' rather than 'Full Screen' to make it clearer?

'Full Screen' makes it sound like it's another size option, like 'Large Desktop', but it isn't really. E.g. If I have 'Small Desktop' selected and then click 'Full Screen', the device width is still set at 'Small Desktop' but it just hides the sidebar.

**Comment by DowleyDeveloped** [comment]
@paulgoodfield Now added in version 3.1.3. Commit found here: https://github.com/towardstudio/websitedocumentation/commit/934b9d0dd08a5362f06b33ea84cc8ed9f0f5e50d

To change in existing projects, you'll need to manually do the updates in the commit
